apiVersion: v1
kind: ConfigMap
metadata:
  name: attendance-config
  namespace: attendance-system
data:
  MYSQL_HOST: "attendance-db"
  MYSQL_DATABASE: "attendance_db"
  MYSQL_USER: "attendance_user"
  FLASK_ENV: "production"
  MAIL_SERVER: "smtp.gmail.com"
  MAIL_PORT: "587"
  ADMIN_USERNAME: "admin"
